version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/Frontend/Dashboard/dashboard-insideugal"
    schedule:
      interval: "weekly"
    assignees:
      - "Raul21000"

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    assignees:
      - "Raul21000"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "Raul21000"