from dataclasses import dataclass
from typing import Any

from fastapi.encoders import jsonable_encoder
from sqlalchemy import bindparam, text
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.translation_utils import normalize_language, translate_payload


@dataclass(frozen=True)
class TranslationCacheConfig:
    table_name: str
    source_table: str
    id_column: str
    id_sql_type: str
    fields: tuple[str, ...]


FACULTY_TRANSLATION = TranslationCacheConfig(
    table_name="faculty_translations",
    source_table="faculties",
    id_column="faculty_id",
    id_sql_type="INTEGER",
    fields=("name", "description", "address"),
)

FACILITY_TRANSLATION = TranslationCacheConfig(
    table_name="facility_translations",
    source_table="facilities",
    id_column="facility_id",
    id_sql_type="INTEGER",
    fields=("name", "description"),
)

LOCATION_TRANSLATION = TranslationCacheConfig(
    table_name="location_translations",
    source_table="locations",
    id_column="location_id",
    id_sql_type="INTEGER",
    fields=("name",),
)

CATEGORY_TRANSLATION = TranslationCacheConfig(
    table_name="category_translations",
    source_table="categories",
    id_column="category_id",
    id_sql_type="INTEGER",
    fields=("name",),
)

PRODUCT_CATEGORY_TRANSLATION = TranslationCacheConfig(
    table_name="product_category_translations",
    source_table="product_categories",
    id_column="category_id",
    id_sql_type="INTEGER",
    fields=("name",),
)

PRODUCT_TRANSLATION = TranslationCacheConfig(
    table_name="product_translations",
    source_table="products",
    id_column="product_id",
    id_sql_type="INTEGER",
    fields=("name", "description"),
)

CITY_GUIDE_CATEGORY_TRANSLATION = TranslationCacheConfig(
    table_name="city_guide_category_translations",
    source_table="city_guide_categories",
    id_column="category_id",
    id_sql_type="VARCHAR(100)",
    fields=("title", "description"),
)

CITY_GUIDE_ITEM_TRANSLATION = TranslationCacheConfig(
    table_name="city_guide_item_translations",
    source_table="city_guide_items",
    id_column="item_id",
    id_sql_type="INTEGER",
    fields=("title", "address"),
)

COMPLAINT_TRANSLATION = TranslationCacheConfig(
    table_name="complaint_translations",
    source_table="complaints",
    id_column="complaint_id",
    id_sql_type="INTEGER",
    fields=("title", "description"),
)

NOTIFICATION_TRANSLATION = TranslationCacheConfig(
    table_name="notification_translations",
    source_table="notifications",
    id_column="notification_id",
    id_sql_type="INTEGER",
    fields=("title", "body"),
)


async def ensure_translation_table(session: AsyncSession, config: TranslationCacheConfig) -> None:
    await session.execute(
        text(
            f"""
            CREATE TABLE IF NOT EXISTS public.{config.table_name} (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                {config.id_column} {config.id_sql_type} NOT NULL REFERENCES public.{config.source_table}(id) ON DELETE CASCADE,
                language_code VARCHAR(10) NOT NULL,
                field_name VARCHAR(100) NOT NULL,
                translated_text TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                CONSTRAINT uq_{config.table_name}_entity_language_field
                    UNIQUE ({config.id_column}, language_code, field_name)
            )
            """
        )
    )
    await session.execute(
        text(
            f"""
            CREATE INDEX IF NOT EXISTS idx_{config.table_name}_{config.id_column}
                ON public.{config.table_name}({config.id_column})
            """
        )
    )
    await session.execute(
        text(
            f"""
            CREATE INDEX IF NOT EXISTS idx_{config.table_name}_language_code
                ON public.{config.table_name}(language_code)
            """
        )
    )
    await session.commit()


async def translate_with_model_cache(
    payload: Any,
    lang: str | None,
    session: AsyncSession,
    config: TranslationCacheConfig,
) -> Any:
    language_code = normalize_language(lang)
    if language_code == "ro":
        return payload

    await ensure_translation_table(session, config)
    encoded_payload: Any
    if isinstance(payload, dict) or (
        isinstance(payload, list) and all(isinstance(item, dict) for item in payload)
    ):
        encoded_payload = payload
    else:
        encoded_payload = jsonable_encoder(payload)
    is_list = isinstance(encoded_payload, list)
    items: list[dict[str, Any]]
    if isinstance(encoded_payload, list):
        items = [item for item in encoded_payload if isinstance(item, dict)]
    elif isinstance(encoded_payload, dict):
        items = [encoded_payload]
    else:
        items = []
    if not items:
        return encoded_payload

    entity_ids = [item.get("id") for item in items if item.get("id") is not None]
    if not entity_ids:
        return encoded_payload

    cached_by_entity: dict[Any, dict[str, str]] = {}
    query = text(
        f"""
        SELECT {config.id_column} AS entity_id, field_name, translated_text
        FROM public.{config.table_name}
        WHERE language_code = :language_code
          AND {config.id_column} IN :entity_ids
        """
    ).bindparams(bindparam("entity_ids", expanding=True))
    result = await session.execute(
        query,
        {"language_code": language_code, "entity_ids": entity_ids},
    )
    for row in result.mappings():
        cached_by_entity.setdefault(row["entity_id"], {})[row["field_name"]] = row["translated_text"]

    missing_payloads: list[dict[str, str]] = []
    missing_items: list[tuple[dict[str, Any], list[str]]] = []
    for item in items:
        entity_id = item.get("id")
        cached_fields = cached_by_entity.get(entity_id, {})
        missing_fields = []
        for field in config.fields:
            value = item.get(field)
            if not isinstance(value, str) or not value.strip():
                continue
            cached_value = cached_fields.get(field)
            if cached_value is not None:
                item[field] = cached_value
            else:
                missing_fields.append(field)

        if missing_fields:
            missing_payloads.append({field: item[field] for field in missing_fields})
            missing_items.append((item, missing_fields))

    if missing_payloads:
        translated_payloads = await translate_payload(
            missing_payloads,
            language_code,
            fields=set(config.fields),
        )
        if isinstance(translated_payloads, list):
            for (item, missing_fields), translated_item in zip(missing_items, translated_payloads):
                if not isinstance(translated_item, dict):
                    continue
                entity_id = item.get("id")
                for field in missing_fields:
                    translated_value = translated_item.get(field)
                    if not isinstance(translated_value, str):
                        continue
                    item[field] = translated_value
                    await _save_field_translation(session, config, entity_id, language_code, field, translated_value)
            await session.commit()

    return encoded_payload if is_list else encoded_payload


async def _save_field_translation(
    session: AsyncSession,
    config: TranslationCacheConfig,
    entity_id: Any,
    language_code: str,
    field_name: str,
    translated_text: str,
) -> None:
    await session.execute(
        text(
            f"""
            INSERT INTO public.{config.table_name}
                ({config.id_column}, language_code, field_name, translated_text)
            VALUES
                (:entity_id, :language_code, :field_name, :translated_text)
            ON CONFLICT ({config.id_column}, language_code, field_name)
            DO UPDATE SET
                translated_text = EXCLUDED.translated_text,
                updated_at = now()
            """
        ),
        {
            "entity_id": entity_id,
            "language_code": language_code,
            "field_name": field_name,
            "translated_text": translated_text,
        },
    )
