export const Config = {
  MAPTILER_STYLE_URL: process.env.EXPO_PUBLIC_MAPTILER_STYLE_URL,
  API_BASE_URL: process.env.EXPO_PUBLIC_API_BASE_URL,
  LLM_BASE_URL: process.env.EXPO_PUBLIC_LLM_BASE_URL,
  DASHBOARD_URL: process.env.EXPO_PUBLIC_DASHBOARD_URL,
};