-- ==========================================================
-- MIGRARE: Traduceri automate pentru anunturi
-- ==========================================================

CREATE TABLE IF NOT EXISTS public.announcement_translations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    announcement_id INTEGER NOT NULL REFERENCES public.announcements(id) ON DELETE CASCADE,
    language_code VARCHAR(10) NOT NULL,
    translated_title VARCHAR(255) NOT NULL,
    translated_content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_announcement_language UNIQUE (announcement_id, language_code)
);

CREATE INDEX IF NOT EXISTS idx_announcement_translations_announcement_id
    ON public.announcement_translations(announcement_id);

CREATE INDEX IF NOT EXISTS idx_announcement_translations_language_code
    ON public.announcement_translations(language_code);
