CREATE TABLE IF NOT EXISTS public.faculty_translations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faculty_id INTEGER NOT NULL REFERENCES public.faculties(id) ON DELETE CASCADE,
    language_code VARCHAR(10) NOT NULL,
    field_name VARCHAR(100) NOT NULL,
    translated_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_faculty_translations_entity_language_field UNIQUE (faculty_id, language_code, field_name)
);

CREATE INDEX IF NOT EXISTS idx_faculty_translations_faculty_id ON public.faculty_translations(faculty_id);
CREATE INDEX IF NOT EXISTS idx_faculty_translations_language_code ON public.faculty_translations(language_code);

CREATE TABLE IF NOT EXISTS public.facility_translations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id INTEGER NOT NULL REFERENCES public.facilities(id) ON DELETE CASCADE,
    language_code VARCHAR(10) NOT NULL,
    field_name VARCHAR(100) NOT NULL,
    translated_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_facility_translations_entity_language_field UNIQUE (facility_id, language_code, field_name)
);

CREATE INDEX IF NOT EXISTS idx_facility_translations_facility_id ON public.facility_translations(facility_id);
CREATE INDEX IF NOT EXISTS idx_facility_translations_language_code ON public.facility_translations(language_code);

CREATE TABLE IF NOT EXISTS public.location_translations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id INTEGER NOT NULL REFERENCES public.locations(id) ON DELETE CASCADE,
    language_code VARCHAR(10) NOT NULL,
    field_name VARCHAR(100) NOT NULL,
    translated_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_location_translations_entity_language_field UNIQUE (location_id, language_code, field_name)
);

CREATE INDEX IF NOT EXISTS idx_location_translations_location_id ON public.location_translations(location_id);
CREATE INDEX IF NOT EXISTS idx_location_translations_language_code ON public.location_translations(language_code);

CREATE TABLE IF NOT EXISTS public.category_translations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INTEGER NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
    language_code VARCHAR(10) NOT NULL,
    field_name VARCHAR(100) NOT NULL,
    translated_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_category_translations_entity_language_field UNIQUE (category_id, language_code, field_name)
);

CREATE INDEX IF NOT EXISTS idx_category_translations_category_id ON public.category_translations(category_id);
CREATE INDEX IF NOT EXISTS idx_category_translations_language_code ON public.category_translations(language_code);

CREATE TABLE IF NOT EXISTS public.product_category_translations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INTEGER NOT NULL REFERENCES public.product_categories(id) ON DELETE CASCADE,
    language_code VARCHAR(10) NOT NULL,
    field_name VARCHAR(100) NOT NULL,
    translated_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_product_category_translations_entity_language_field UNIQUE (category_id, language_code, field_name)
);

CREATE INDEX IF NOT EXISTS idx_product_category_translations_category_id ON public.product_category_translations(category_id);
CREATE INDEX IF NOT EXISTS idx_product_category_translations_language_code ON public.product_category_translations(language_code);

CREATE TABLE IF NOT EXISTS public.product_translations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    language_code VARCHAR(10) NOT NULL,
    field_name VARCHAR(100) NOT NULL,
    translated_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_product_translations_entity_language_field UNIQUE (product_id, language_code, field_name)
);

CREATE INDEX IF NOT EXISTS idx_product_translations_product_id ON public.product_translations(product_id);
CREATE INDEX IF NOT EXISTS idx_product_translations_language_code ON public.product_translations(language_code);

CREATE TABLE IF NOT EXISTS public.city_guide_categories (
    id VARCHAR PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    icon_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.city_guide_items (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    category_id VARCHAR NOT NULL REFERENCES public.city_guide_categories(id) ON DELETE CASCADE,
    image_url TEXT,
    address TEXT,
    website TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.city_guide_category_translations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id VARCHAR(100) NOT NULL REFERENCES public.city_guide_categories(id) ON DELETE CASCADE,
    language_code VARCHAR(10) NOT NULL,
    field_name VARCHAR(100) NOT NULL,
    translated_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_city_guide_category_translations_entity_language_field UNIQUE (category_id, language_code, field_name)
);

CREATE INDEX IF NOT EXISTS idx_city_guide_category_translations_category_id ON public.city_guide_category_translations(category_id);
CREATE INDEX IF NOT EXISTS idx_city_guide_category_translations_language_code ON public.city_guide_category_translations(language_code);

CREATE TABLE IF NOT EXISTS public.city_guide_item_translations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER NOT NULL REFERENCES public.city_guide_items(id) ON DELETE CASCADE,
    language_code VARCHAR(10) NOT NULL,
    field_name VARCHAR(100) NOT NULL,
    translated_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_city_guide_item_translations_entity_language_field UNIQUE (item_id, language_code, field_name)
);

CREATE INDEX IF NOT EXISTS idx_city_guide_item_translations_item_id ON public.city_guide_item_translations(item_id);
CREATE INDEX IF NOT EXISTS idx_city_guide_item_translations_language_code ON public.city_guide_item_translations(language_code);

CREATE TABLE IF NOT EXISTS public.complaint_translations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_id INTEGER NOT NULL REFERENCES public.complaints(id) ON DELETE CASCADE,
    language_code VARCHAR(10) NOT NULL,
    field_name VARCHAR(100) NOT NULL,
    translated_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_complaint_translations_entity_language_field UNIQUE (complaint_id, language_code, field_name)
);

CREATE INDEX IF NOT EXISTS idx_complaint_translations_complaint_id ON public.complaint_translations(complaint_id);
CREATE INDEX IF NOT EXISTS idx_complaint_translations_language_code ON public.complaint_translations(language_code);

CREATE TABLE IF NOT EXISTS public.notification_translations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id INTEGER NOT NULL REFERENCES public.notifications(id) ON DELETE CASCADE,
    language_code VARCHAR(10) NOT NULL,
    field_name VARCHAR(100) NOT NULL,
    translated_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_notification_translations_entity_language_field UNIQUE (notification_id, language_code, field_name)
);

CREATE INDEX IF NOT EXISTS idx_notification_translations_notification_id ON public.notification_translations(notification_id);
CREATE INDEX IF NOT EXISTS idx_notification_translations_language_code ON public.notification_translations(language_code);
